---
- name: Create Joke Database
  hosts: Datenbank
  become: yes
  gather_facts: yes

  vars:
    db_name: jokedb
    db_user: jokedbuser
    db_password: "123456"

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install MariaDB Server
      ansible.builtin.apt:
        name: mariadb-server
        state: present

    - name: Install PyMySQL for Ansible MySQL modules
      ansible.builtin.apt:
        name: python3-pymysql
        state: present

    - name: Allow MariaDB to listen on all interfaces
      ansible.builtin.replace:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address\s*=.*'
        replace: 'bind-address = 0.0.0.0'
      notify: Restart MariaDB

    - name: Ensure MariaDB is running
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create Joke Database
      community.mysql.mysql_db:
        name: "{{ db_name }}"
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Create User for localhost
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        host: "localhost"
        priv: "{{ db_name }}.*:ALL"
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Create User for remote %
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        host: "%"
        priv: "{{ db_name }}.*:ALL"
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Flush MySQL Privileges
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        state: present
        check_implicit_admin: yes
        login_unix_socket: /run/mysqld/mysqld.sock

  handlers:
    - name: Restart MariaDB
      ansible.builtin.service:
        name: mariadb
        state: restarted
